import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";

/**
 * Typed loader for the curriculum maps in docs/content/*.json (AP-13).
 * Each JSON is the contract the plan and generate agents follow (AP-14).
 * Sources are official only (Ausbildungsordnung, Anlage, KMK Rahmenlehrplan);
 * no IHK exam copies, no PII. Markdown next to each JSON is generated by
 * scripts/content-render-curriculum.mjs and never edited by hand.
 */
export type QuestionType = "auswahl" | "zuordnen" | "lueckentext" | "reihenfolge" | "rechnen";
export type QuestionMix = Record<QuestionType, number>;

export type CurriculumSource = {
  id: string;
  title: string;
  url: string;
  kind: "ausbildungsordnung" | "rahmenlehrplan" | "pruefung" | "berufsinformation" | "empfehlung";
  fetchedAt: string;
  via: string;
};

export type CurriculumBlock = {
  id: string;
  title: string;
  units: number;
  topics: string[];
  sourceIds: string[];
  rechnen?: boolean;
  safety?: boolean;
};

export type AoPosition = {
  /** Human-readable reference, e.g. "Anlage I Nr. 5" or "Anlage A Nr. 3". */
  ref: string;
  /** Key into aoBerufsbild, e.g. "4" or "A3". */
  berufsbild: string;
};

export type CurriculumModule = {
  id: string;
  order: number;
  title: string;
  kind: "querschnitt" | "lernfeld" | "ao-kern" | "wiso" | "pruefung";
  year: 1 | 2 | 3;
  niveau: string;
  rlpLernfeld?: { nr: number; label?: string; title: string; hours: number; sourceId: string; viaSourceId?: string };
  aoPositions: AoPosition[];
  examAreas: string[];
  unitsTarget: number;
  safety: boolean;
  questionMix: QuestionMix;
  note?: string;
  blocks: CurriculumBlock[];
};

export type ZeitrahmenRow = {
  lfdNr: string[];
  berufsbild: string[];
  weeks: number | null;
  note?: string;
};

export type ZeitrahmenSection = {
  id: string;
  title: string;
  sourceId: string;
  /** Expected sum of the numeric week values, or null when the Anlage gives none. */
  expectedWeeks: number | null;
  rows: ZeitrahmenRow[];
};

export type ExamPart = {
  id: string;
  part: string;
  bereich: string;
  form: "schriftlich" | "praktisch" | "betrieblich";
  duration?: string;
  /** null for parts that must be passed but carry no percentage (e.g. MAF praktischer Teil). */
  weightPercent: number | null;
  gebiete: Array<{ id: string; title: string }>;
  sourceId: string;
};

export type CurriculumPhase = {
  id: string;
  title: string;
  moduleIds: string[];
  why: string;
  unitsTarget: number;
};

export type Curriculum = {
  id: string;
  family: string;
  title: string;
  version: string;
  status: string;
  keyword: string;
  variantLabel?: string;
  durationYears: number;
  durationNote: string;
  referenceRlp: { sourceId: string; why: string; alternatives: string[] };
  unit: {
    minutesMin: number;
    minutesMax: number;
    minutesAvg: number;
    questionsMin: number;
    questionsMax: number;
    questionTypes: QuestionType[];
    explanationWithSource: boolean;
  };
  defaultQuestionMix: QuestionMix;
  rules: string[];
  assumptions: string[];
  aoBerufsbild: Array<{ id: string; title: string }>;
  aoZeitrahmen: { sections: ZeitrahmenSection[] };
  exam: {
    summary: string;
    gradedParts: ExamPart[];
    ungraded: Array<{ id: string; title: string; text: string; sourceId: string }>;
    bestehen: string;
  };
  totals: {
    modules: number;
    unitsTarget: number;
    hoursAtAvgUnit: number;
    questionsMin: number;
    questionsMax: number;
    rlpHoursByYear: Record<string, number>;
  };
  phases: CurriculumPhase[];
  modules: CurriculumModule[];
  sources: CurriculumSource[];
};

export const CONTENT_DIR = path.join(process.cwd(), "docs", "content");

/** Pilot map (Metall- und Kunststofftechnik, Referenz Industriemechaniker). */
export const MAF_METALL_PATH = path.join(CONTENT_DIR, "maf-metall.json");

export function listCurriculumFiles(dir: string = CONTENT_DIR): string[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json") && !f.endsWith(".lock.json"))
    .sort()
    .map((f) => path.join(dir, f));
}

export function loadCurriculum(file: string): Curriculum {
  return JSON.parse(readFileSync(file, "utf8")) as Curriculum;
}

export function loadAllCurricula(dir: string = CONTENT_DIR): Curriculum[] {
  return listCurriculumFiles(dir).map(loadCurriculum);
}

/** Backwards-compatible entry point used by the pilot pipeline. */
export function loadMafCurriculum(file: string = MAF_METALL_PATH): Curriculum {
  return loadCurriculum(file);
}

/** Recompute totals from modules so the stored `totals` block can be verified. */
export function curriculumTotals(c: Curriculum): Curriculum["totals"] {
  const unitsTarget = c.modules.reduce((s, m) => s + m.unitsTarget, 0);
  const rlpHoursByYear: Record<string, number> = {};
  for (const m of c.modules) {
    if (m.kind !== "lernfeld" || !m.rlpLernfeld) continue;
    rlpHoursByYear[String(m.year)] = (rlpHoursByYear[String(m.year)] ?? 0) + m.rlpLernfeld.hours;
  }
  return {
    modules: c.modules.length,
    unitsTarget,
    hoursAtAvgUnit: Math.round(((unitsTarget * c.unit.minutesAvg) / 60) * 10) / 10,
    questionsMin: unitsTarget * c.unit.questionsMin,
    questionsMax: unitsTarget * c.unit.questionsMax,
    rlpHoursByYear,
  };
}

/** Modules of one generation phase, in learning order. */
export function modulesForPhase(c: Curriculum, phaseId: string): CurriculumModule[] {
  const phase = c.phases.find((p) => p.id === phaseId);
  if (!phase) return [];
  return c.modules.filter((m) => phase.moduleIds.includes(m.id)).sort((a, b) => a.order - b.order);
}

/** Resolve a block's official source records for the generate prompt. */
export function blockSources(c: Curriculum, block: CurriculumBlock): CurriculumSource[] {
  return block.sourceIds
    .map((id) => c.sources.find((s) => s.id === id))
    .filter((s): s is CurriculumSource => Boolean(s));
}

/** All exam area ids a module may reference: graded part ids, their Gebiete, ungraded ids. */
export function examAreaIds(c: Curriculum): Set<string> {
  const ids = new Set<string>();
  for (const p of c.exam.gradedParts) {
    ids.add(p.id);
    for (const g of p.gebiete) ids.add(g.id);
  }
  for (const u of c.exam.ungraded) ids.add(u.id);
  return ids;
}
