// SIN-257: alle Routen unter src/app (dynamische Route mit Beispiel-ID).
export const routes = [
  "/",
  "/start",
  "/demo",
  "/anmelden",
  "/ausbilder",
  "/pruefung/ergebnis",
  "/willkommen",
  "/einwilligung",
  "/beruf",
  "/schwerpunkt",
  "/lernpfad",
  "/einheit/unit-03",
  "/ergebnis",
  "/wiederholung",
  "/pruefung",
  "/profil",
  "/einstellungen",
  "/impressum",
  "/datenschutz",
  "/ki-hinweis",
  "/quellen",
];
